name: todoflex
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Add your dependencies here
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  sqflite: ^2.3.0
  path_provider: ^2.1.0
  uuid: ^4.3.3
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  js: ^0.6.7
  firebase_core_web: ^2.10.0
  firebase_auth_web: ^5.8.12
  cloud_firestore_web: ^3.8.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
