// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_BuTNxXOXKcKI_S2O16VZ6AoRysM7pew',
    appId: '1:921360040103:web:27c2da1791e758f6b3db82',
    messagingSenderId: '921360040103',
    projectId: 'todoflex-app-shahzaib-2b579',
    authDomain: 'todoflex-app-shahzaib-2b579.firebaseapp.com',
    storageBucket: 'todoflex-app-shahzaib-2b579.firebasestorage.app',
    measurementId: 'G-D494F911PR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_BuTNxXOXKcKI_S2O16VZ6AoRysM7pew',
    appId: '1:921360040103:web:27c2da1791e758f6b3db82',
    messagingSenderId: '921360040103',
    projectId: 'todoflex-app-shahzaib-2b579',
    storageBucket: 'todoflex-app-shahzaib-2b579.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_BuTNxXOXKcKI_S2O16VZ6AoRysM7pew',
    appId: '1:921360040103:web:27c2da1791e758f6b3db82',
    messagingSenderId: '921360040103',
    projectId: 'todoflex-app-shahzaib-2b579',
    storageBucket: 'todoflex-app-shahzaib-2b579.firebasestorage.app',
    iosClientId: 'YOUR-IOS-CLIENT-ID',
    iosBundleId: 'com.example.todoflex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_BuTNxXOXKcKI_S2O16VZ6AoRysM7pew',
    appId: '1:921360040103:web:27c2da1791e758f6b3db82',
    messagingSenderId: '921360040103',
    projectId: 'todoflex-app-shahzaib-2b579',
    storageBucket: 'todoflex-app-shahzaib-2b579.firebasestorage.app',
    iosClientId: 'YOUR-MACOS-CLIENT-ID',
    iosBundleId: 'com.example.todoflex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_BuTNxXOXKcKI_S2O16VZ6AoRysM7pew',
    appId: '1:921360040103:web:27c2da1791e758f6b3db82',
    messagingSenderId: '921360040103',
    projectId: 'todoflex-app-shahzaib-2b579',
    storageBucket: 'todoflex-app-shahzaib-2b579.firebasestorage.app',
  );
}
